let shopItemsData = [
    {
        id: "FM001",
        name: 'JAM & POPPY SEED BITES',
        price: 0.99,
        img: 'image/1.png',
        imgHover: 'image/1a.png',
    },
    {
        id: "FM002",
        name: 'POPPY SEEDS BITES',
        price: 1.99,
        img: 'image/2.png',
        imgHover: 'image/2a.png',
    },
    {
        id: "FM003",
        name: 'OATMEAL BITES',
        price: 1.99,
        img: 'image/3.png',
        imgHover: 'image/3a.png',
    },
    {
        id: "FM004",
        name: 'SOFT BUTTER COOKIES',
        price: 1.99,
        img: 'image/4.png',
        imgHover: 'image/4a.png',
    },
    {
        id: "FM005",
        name: 'PARMESAN BITES',
        price: 1.99,
        img: 'image/5.png',
        imgHover: 'image/5a.png',
    },
    {
        id: "FM006",
        name: 'WHITE CHOCOLATE BITES',
        price: 0.99,
        img: 'image/6.png',
        imgHover: 'image/6a.png',
    },
    {
        id: "FM007",
        name: 'JAM BITES',
        price: 0.99,
        img: 'image/7.png',
        imgHover: 'image/7a.png',
    },
    {
        id: "FM008",
        name: 'CHOCOLATE CHIPS',
        price: 1.99,
        img: 'image/8.png',
        imgHover: 'image/8a.png',
    },
    {
        id: "FM009",
        name: 'NUTS & CARAMEL BITES',
        price: 1.99,
        img: 'image/9.png',
        imgHover: 'image/9a.png',
    },
    {
        id: "FM010",
        name: 'BUTTER COOKIES',
        price: 1.99,
        img: 'image/10.png',
        imgHover: 'image/10a.png',
    },
    {
        id: "FM011",
        name: 'PECAN NUT BITES',
        price: 1.99,
        img: 'image/11.jpg',
        imgHover: 'image/11a.jpg',
    },
    {
        id: "FM012",
        name: 'SEEDS BITES',
        price: 1.99,
        img: 'image/12.jpg',
        imgHover: 'image/12a.jpg',
    },
]